# Generated by Django 3.1.8 on 2021-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210722_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_bpm', models.TextField(max_length=50)),
                ('height', models.FloatField(max_length=50)),
                ('avg_bpm', models.FloatField(max_length=50)),
                ('temperature', models.FloatField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('fall', models.BooleanField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Woker',
        ),
    ]
