# Generated by Django 3.1.8 on 2021-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210722_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='curr_bpm',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
