# Generated by Django 3.1.8 on 2021-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210722_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(),
        ),
    ]
