# Generated by Django 3.1.8 on 2021-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210722_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
