# Generated by Django 3.1.8 on 2021-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210722_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='time',
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
