# Generated by Django 3.1.8 on 2021-07-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210722_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='date',
        ),
    ]
