# Generated by Django 3.1.8 on 2021-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_worker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fall',
            field=models.BooleanField(default=False),
        ),
    ]
