# Generated by Django 3.2.5 on 2021-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_logs_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
