# Generated by Django 3.2.5 on 2021-08-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210807_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
