# Generated by Django 3.2.5 on 2021-08-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_log_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='worker_id',
            field=models.ForeignKey(blank=-1, on_delete=django.db.models.deletion.CASCADE, to='home.worker'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('Present', models.BooleanField(default=False)),
                ('worker_id', models.ForeignKey(blank=-1, on_delete=django.db.models.deletion.CASCADE, to='home.worker')),
            ],
        ),
    ]
