# Generated by Django 3.2.5 on 2021-08-07 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210807_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
