# Generated by Django 3.2.5 on 2021-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_log_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='Offline', max_length=15),
        ),
    ]
