# Generated by Django 3.2.5 on 2021-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(default='Offline', max_length=15),
        ),
    ]
